name: Enviar paso de bachata diario

on:
  schedule:
    - cron: "0 7 * * *"  # 7 AM UTC = 9 AM en España
  workflow_dispatch:     # Permite ejecutarlo manualmente

jobs:
  enviar-correo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar el script
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python enviar_bachata.py
